import { ConceptCard, H2 } from '../GuideParts';

export function ConceptsSection() {
  return (
  <div className="flex flex-col gap-4">
    <H2>Concepts</H2>
    <div className="grid gap-3 sm:grid-cols-2">
      <ConceptCard title="Source">
        A connection to where your data lives: an uploaded file, a database, a URL, or a Google Sheet.
      </ConceptCard>
      <ConceptCard title="Dataset">
        A physical table ingested from a source (or derived from other datasets). This is what you query.
      </ConceptCard>
      <ConceptCard title="Query">
        A question — written in SQL by you, or generated by the AI from plain language — run against datasets.
      </ConceptCard>
      <ConceptCard title="Chart">
        A saved visualization of a query result (bar, line, table, …). Charts are the building blocks of
        dashboards.
      </ConceptCard>
      <ConceptCard title="Dashboard">
        A collection of charts arranged on draggable, resizable tiles across one or more pages.
      </ConceptCard>
      <ConceptCard title="Metric">
        A semantic-layer definition of a business measure (e.g. “Monthly Revenue”) with dimensions and an owner
        — defined once, used everywhere.
      </ConceptCard>
      <ConceptCard title="Verified query library">
        AI answers your team has marked as correct (✓). They’re reused as trusted examples for future
        questions.
      </ConceptCard>
      <ConceptCard title="Alert">
        A rule on a chart or metric that’s checked on a schedule and notifies you when it triggers.
      </ConceptCard>
      <ConceptCard title="Quality check">
        An automated validation on a dataset — nulls, uniqueness, ranges, freshness — surfaced as badges.
      </ConceptCard>
      <ConceptCard title="Lineage">
        The trace of where data comes from: source → dataset → transforms → charts → dashboard tiles.
      </ConceptCard>
    </div>
  </div>
  );
}
